name: Deploy Dev

on:
  push:
    branches:
      - develop
    repository_dispatch:

jobs:
  build:
    env:
      VUE_APP_TITAN_BRANCH: develop
      VUE_APP_GH_TOKEN: ${{ secrets.VUE_APP_GITHUB_TOKEN }}


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm intall, fetch data
      run: |
        npm install
    - name: npm build
      env:
        NODE_ENV: production
        BASE_URL: /behavioral-task-hub/
      run: |
        npm run build
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist