name: Deploy Firebase

on:
  push:
    branches:
      - bootstrap-theme
    repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      env:
        VUE_APP_GITHUB_TOKEN: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
        VUE_APP_GITHUB_USER: ${{ secrets.VUE_APP_GITHUB_USER }}
      run: |
        npm install
    - name: test
      run: |
        npm run test:unit
    - name: npm build
      env:
        NODE_ENV: production
      run: |
        npm run build
    - name: Deploy to Firebase
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm run deploy 