name: Deploy Firebase

on:
  push:
    branches:
      - master
    repository_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      env:
        VUE_APP_GITHUB_TOKEN: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
        VUE_APP_GITHUB_USER: ${{ secrets.VUE_APP_GITHUB_USER }}
      run: |
        npm install
    - name: npm build
      env:
        NODE_ENV: production
      run: |
        npm run build
    - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
